# coding: utf-8

"""
    Lago API documentation

    Lago API allows your application to push customer information and metrics (events) from your application to the billing application.

    The version of the OpenAPI document: 0.52.0-beta
    Contact: tech@getlago.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from lago_api.models.coupons_paginated import CouponsPaginated

class TestCouponsPaginated(unittest.TestCase):
    """CouponsPaginated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CouponsPaginated:
        """Test CouponsPaginated
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CouponsPaginated`
        """
        model = CouponsPaginated()
        if include_optional:
            return CouponsPaginated(
                coupons = [
                    lago_api.models.coupon_object.CouponObject(
                        lago_id = '1a901a90-1a90-1a90-1a90-1a901a901a90', 
                        name = 'Startup Deal', 
                        code = 'startup_deal', 
                        description = 'I am a coupon description', 
                        coupon_type = 'fixed_amount', 
                        amount_cents = 5000, 
                        amount_currency = null, 
                        reusable = True, 
                        limited_plans = True, 
                        plan_codes = ["startup_plan"], 
                        limited_billable_metrics = False, 
                        billable_metric_codes = [], 
                        percentage_rate = '472888001528021798096225500850762', 
                        frequency = 'recurring', 
                        frequency_duration = 6, 
                        expiration = 'time_limit', 
                        expiration_at = '2022-08-08T23:59:59Z', 
                        created_at = '2022-04-29T08:59:51Z', 
                        terminated_at = '2022-08-08T23:59:59Z', )
                    ],
                meta = lago_api.models.pagination_meta.PaginationMeta(
                    current_page = 2, 
                    next_page = 3, 
                    prev_page = 1, 
                    total_pages = 4, 
                    total_count = 70, )
            )
        else:
            return CouponsPaginated(
                coupons = [
                    lago_api.models.coupon_object.CouponObject(
                        lago_id = '1a901a90-1a90-1a90-1a90-1a901a901a90', 
                        name = 'Startup Deal', 
                        code = 'startup_deal', 
                        description = 'I am a coupon description', 
                        coupon_type = 'fixed_amount', 
                        amount_cents = 5000, 
                        amount_currency = null, 
                        reusable = True, 
                        limited_plans = True, 
                        plan_codes = ["startup_plan"], 
                        limited_billable_metrics = False, 
                        billable_metric_codes = [], 
                        percentage_rate = '472888001528021798096225500850762', 
                        frequency = 'recurring', 
                        frequency_duration = 6, 
                        expiration = 'time_limit', 
                        expiration_at = '2022-08-08T23:59:59Z', 
                        created_at = '2022-04-29T08:59:51Z', 
                        terminated_at = '2022-08-08T23:59:59Z', )
                    ],
                meta = lago_api.models.pagination_meta.PaginationMeta(
                    current_page = 2, 
                    next_page = 3, 
                    prev_page = 1, 
                    total_pages = 4, 
                    total_count = 70, ),
        )
        """

    def testCouponsPaginated(self):
        """Test CouponsPaginated"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
