# coding: utf-8

"""
    Lago API documentation

    Lago API allows your application to push customer information and metrics (events) from your application to the billing application.

    The version of the OpenAPI document: 0.52.0-beta
    Contact: tech@getlago.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from lago_api.models.get_customer_portal_url200_response_customer import GetCustomerPortalUrl200ResponseCustomer

class TestGetCustomerPortalUrl200ResponseCustomer(unittest.TestCase):
    """GetCustomerPortalUrl200ResponseCustomer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCustomerPortalUrl200ResponseCustomer:
        """Test GetCustomerPortalUrl200ResponseCustomer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCustomerPortalUrl200ResponseCustomer`
        """
        model = GetCustomerPortalUrl200ResponseCustomer()
        if include_optional:
            return GetCustomerPortalUrl200ResponseCustomer(
                portal_url = 'https://app.lago.com/customer-portal/1234567890'
            )
        else:
            return GetCustomerPortalUrl200ResponseCustomer(
                portal_url = 'https://app.lago.com/customer-portal/1234567890',
        )
        """

    def testGetCustomerPortalUrl200ResponseCustomer(self):
        """Test GetCustomerPortalUrl200ResponseCustomer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
