# coding: utf-8

"""
    Lago API documentation

    Lago API allows your application to push customer information and metrics (events) from your application to the billing application.

    The version of the OpenAPI document: 0.52.0-beta
    Contact: tech@getlago.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from lago_api.models.tax_object import TaxObject

class TestTaxObject(unittest.TestCase):
    """TaxObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaxObject:
        """Test TaxObject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaxObject`
        """
        model = TaxObject()
        if include_optional:
            return TaxObject(
                lago_id = '1a901a90-1a90-1a90-1a90-1a901a901a90',
                name = 'TVA',
                code = 'french_standard_vat',
                description = 'French standard VAT',
                rate = 20,
                applied_to_organization = True,
                add_ons_count = 0,
                charges_count = 0,
                customers_count = 0,
                plans_count = 0,
                created_at = '2023-07-06T14:35:58Z'
            )
        else:
            return TaxObject(
                lago_id = '1a901a90-1a90-1a90-1a90-1a901a901a90',
                name = 'TVA',
                code = 'french_standard_vat',
                rate = 20,
                applied_to_organization = True,
                customers_count = 0,
                created_at = '2023-07-06T14:35:58Z',
        )
        """

    def testTaxObject(self):
        """Test TaxObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
