# coding: utf-8

"""
    Lago API documentation

    Lago API allows your application to push customer information and metrics (events) from your application to the billing application.

    The version of the OpenAPI document: 0.52.0-beta
    Contact: tech@getlago.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr
from pydantic import Field
from lago_api.models.credit_note_estimated_estimated_credit_note_applied_taxes_inner import CreditNoteEstimatedEstimatedCreditNoteAppliedTaxesInner
from lago_api.models.credit_note_estimated_estimated_credit_note_items_inner import CreditNoteEstimatedEstimatedCreditNoteItemsInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CreditNoteEstimatedEstimatedCreditNote(BaseModel):
    """
    CreditNoteEstimatedEstimatedCreditNote
    """ # noqa: E501
    lago_invoice_id: StrictStr = Field(description="Unique identifier assigned to the invoice that the credit note belongs to")
    invoice_number: StrictStr = Field(description="The invoice unique number, related to the credit note.")
    currency: Any
    taxes_amount_cents: StrictInt = Field(description="The tax amount of the credit note, expressed in cents.")
    taxes_rate: Union[StrictFloat, StrictInt] = Field(description="The tax rate associated with this specific credit note.")
    sub_total_excluding_taxes_amount_cents: StrictInt = Field(description="The subtotal of the credit note excluding any applicable taxes, expressed in cents.")
    max_creditable_amount_cents: StrictInt = Field(description="The credited amount of the credit note, expressed in cents.")
    max_refundable_amount_cents: StrictInt = Field(description="The refunded amount of the credit note, expressed in cents.")
    coupons_adjustment_amount_cents: StrictInt = Field(description="The pro-rated amount of the coupons applied to the source invoice.")
    items: List[CreditNoteEstimatedEstimatedCreditNoteItemsInner] = Field(description="Array of credit note’s items.")
    applied_taxes: Optional[List[CreditNoteEstimatedEstimatedCreditNoteAppliedTaxesInner]] = None
    __properties: ClassVar[List[str]] = ["lago_invoice_id", "invoice_number", "currency", "taxes_amount_cents", "taxes_rate", "sub_total_excluding_taxes_amount_cents", "max_creditable_amount_cents", "max_refundable_amount_cents", "coupons_adjustment_amount_cents", "items", "applied_taxes"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CreditNoteEstimatedEstimatedCreditNote from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of currency
        if self.currency:
            _dict['currency'] = self.currency.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item in self.items:
                if _item:
                    _items.append(_item.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in applied_taxes (list)
        _items = []
        if self.applied_taxes:
            for _item in self.applied_taxes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['applied_taxes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CreditNoteEstimatedEstimatedCreditNote from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lago_invoice_id": obj.get("lago_invoice_id"),
            "invoice_number": obj.get("invoice_number"),
            "currency": Currency.from_dict(obj.get("currency")) if obj.get("currency") is not None else None,
            "taxes_amount_cents": obj.get("taxes_amount_cents"),
            "taxes_rate": obj.get("taxes_rate"),
            "sub_total_excluding_taxes_amount_cents": obj.get("sub_total_excluding_taxes_amount_cents"),
            "max_creditable_amount_cents": obj.get("max_creditable_amount_cents"),
            "max_refundable_amount_cents": obj.get("max_refundable_amount_cents"),
            "coupons_adjustment_amount_cents": obj.get("coupons_adjustment_amount_cents"),
            "items": [CreditNoteEstimatedEstimatedCreditNoteItemsInner.from_dict(_item) for _item in obj.get("items")] if obj.get("items") is not None else None,
            "applied_taxes": [CreditNoteEstimatedEstimatedCreditNoteAppliedTaxesInner.from_dict(_item) for _item in obj.get("applied_taxes")] if obj.get("applied_taxes") is not None else None
        })
        return _obj


