=begin
#Lago API documentation

#Lago API allows your application to push customer information and metrics (events) from your application to the billing application.

The version of the OpenAPI document: 0.51.0-beta
Contact: tech@getlago.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for LagoAPI::AnalyticsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AnalyticsApi' do
  before do
    # run before each test
    @api_instance = LagoAPI::AnalyticsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AnalyticsApi' do
    it 'should create an instance of AnalyticsApi' do
      expect(@api_instance).to be_instance_of(LagoAPI::AnalyticsApi)
    end
  end

  # unit tests for find_all_gross_revenues
  # List gross revenue
  # Gross revenue is the sum of monthly &#x60;finalized&#x60; invoice payments and fees paid in advance that are not invoiceable. This total is calculated after deducting taxes and discounts.
  # @param [Hash] opts the optional parameters
  # @option opts [Currency] :currency Currency of revenue analytics. Format must be ISO 4217.
  # @option opts [String] :external_customer_id The customer external unique identifier (provided by your own application). Use it to filter revenue analytics at the customer level.
  # @return [GrossRevenues]
  describe 'find_all_gross_revenues test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for find_all_invoiced_usages
  # List usage revenue
  # Reports a monthly analysis focused on the revenue generated from all usage-based fees. It exclusively accounts for revenue that has been formally invoiced. Importantly, this report does not include revenue related to the usage in the current billing period, limiting its scope to previously invoiced amounts.
  # @param [Hash] opts the optional parameters
  # @option opts [Currency] :currency The currency of invoiced usage analytics. Format must be ISO 4217.
  # @return [InvoicedUsages]
  describe 'find_all_invoiced_usages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for find_all_mrrs
  # List MRR
  # This endpoint is used to list MRR.
  # @param [Hash] opts the optional parameters
  # @option opts [Currency] :currency Quantifies the revenue generated from &#x60;subscription&#x60; fees on a monthly basis. This figure is calculated post-application of applicable taxes and prior to the deduction of any applicable discounts. The method of calculation varies based on the subscription billing cycle:  - Revenue from &#x60;monthly&#x60; subscription invoices is included in the MRR for the month in which the invoice is issued. - Revenue from &#x60;quarterly&#x60; subscription invoices is distributed evenly over three months. This distribution applies to fees paid in advance (allocated to the next three months) as well as to fees paid in arrears (allocated to the preceding three months). - Revenue from &#x60;yearly&#x60; subscription invoices is distributed evenly over twelve months. This allocation is applicable for fees paid in advance (spread over the next twelve months) and for fees paid in arrears (spread over the previous twelve months). - Revenue from &#x60;weekly&#x60; subscription invoices, the total revenue from all invoices issued within a month is summed up. This total is then divided by the number of invoices issued during that month, and the result is multiplied by 4.33, representing the average number of weeks in a month.
  # @option opts [Integer] :months Show data only for given number of months.
  # @return [Mrrs]
  describe 'find_all_mrrs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for find_all_outstanding_invoices
  # List outstanding invoices
  # Represents a monthly aggregation, detailing both the total count and the cumulative amount of invoices that have been marked as &#x60;finalized&#x60;. This report sorts invoices categorically based on their &#x60;payment_status&#x60;.
  # @param [Hash] opts the optional parameters
  # @option opts [Currency] :currency The currency of revenue analytics. Format must be ISO 4217.
  # @return [OutstandingInvoices]
  describe 'find_all_outstanding_invoices test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
