/*
Lago API documentation

Lago API allows your application to push customer information and metrics (events) from your application to the billing application.

API version: 0.52.0-beta
Contact: tech@getlago.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lagoapi

import (
	"encoding/json"
)

// checks if the PlanOverridesObjectChargesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlanOverridesObjectChargesInner{}

// PlanOverridesObjectChargesInner struct for PlanOverridesObjectChargesInner
type PlanOverridesObjectChargesInner struct {
	// Unique identifier of the charge created by Lago.
	Id *string `json:"id,omitempty"`
	// Unique identifier of the billable metric created by Lago.
	BillableMetricId *string `json:"billable_metric_id,omitempty"`
	// Specifies the name that will be displayed on an invoice. If no value is set for this field, the name of the actual charge will be used as the default display name.
	InvoiceDisplayName *string `json:"invoice_display_name,omitempty"`
	// The minimum spending amount required for the charge, measured in cents and excluding any applicable taxes. It indicates the minimum amount that needs to be charged for each billing period.
	MinAmountCents *int32 `json:"min_amount_cents,omitempty"`
	Properties *ChargeObjectProperties `json:"properties,omitempty"`
	// All charge information, sorted by groups.
	GroupProperties []PlanCreateInputPlanChargesInnerGroupPropertiesInner `json:"group_properties,omitempty"`
	// List of unique code used to identify the taxes.
	TaxCodes []string `json:"tax_codes,omitempty"`
}

// NewPlanOverridesObjectChargesInner instantiates a new PlanOverridesObjectChargesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanOverridesObjectChargesInner() *PlanOverridesObjectChargesInner {
	this := PlanOverridesObjectChargesInner{}
	return &this
}

// NewPlanOverridesObjectChargesInnerWithDefaults instantiates a new PlanOverridesObjectChargesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanOverridesObjectChargesInnerWithDefaults() *PlanOverridesObjectChargesInner {
	this := PlanOverridesObjectChargesInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PlanOverridesObjectChargesInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanOverridesObjectChargesInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PlanOverridesObjectChargesInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PlanOverridesObjectChargesInner) SetId(v string) {
	o.Id = &v
}

// GetBillableMetricId returns the BillableMetricId field value if set, zero value otherwise.
func (o *PlanOverridesObjectChargesInner) GetBillableMetricId() string {
	if o == nil || IsNil(o.BillableMetricId) {
		var ret string
		return ret
	}
	return *o.BillableMetricId
}

// GetBillableMetricIdOk returns a tuple with the BillableMetricId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanOverridesObjectChargesInner) GetBillableMetricIdOk() (*string, bool) {
	if o == nil || IsNil(o.BillableMetricId) {
		return nil, false
	}
	return o.BillableMetricId, true
}

// HasBillableMetricId returns a boolean if a field has been set.
func (o *PlanOverridesObjectChargesInner) HasBillableMetricId() bool {
	if o != nil && !IsNil(o.BillableMetricId) {
		return true
	}

	return false
}

// SetBillableMetricId gets a reference to the given string and assigns it to the BillableMetricId field.
func (o *PlanOverridesObjectChargesInner) SetBillableMetricId(v string) {
	o.BillableMetricId = &v
}

// GetInvoiceDisplayName returns the InvoiceDisplayName field value if set, zero value otherwise.
func (o *PlanOverridesObjectChargesInner) GetInvoiceDisplayName() string {
	if o == nil || IsNil(o.InvoiceDisplayName) {
		var ret string
		return ret
	}
	return *o.InvoiceDisplayName
}

// GetInvoiceDisplayNameOk returns a tuple with the InvoiceDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanOverridesObjectChargesInner) GetInvoiceDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceDisplayName) {
		return nil, false
	}
	return o.InvoiceDisplayName, true
}

// HasInvoiceDisplayName returns a boolean if a field has been set.
func (o *PlanOverridesObjectChargesInner) HasInvoiceDisplayName() bool {
	if o != nil && !IsNil(o.InvoiceDisplayName) {
		return true
	}

	return false
}

// SetInvoiceDisplayName gets a reference to the given string and assigns it to the InvoiceDisplayName field.
func (o *PlanOverridesObjectChargesInner) SetInvoiceDisplayName(v string) {
	o.InvoiceDisplayName = &v
}

// GetMinAmountCents returns the MinAmountCents field value if set, zero value otherwise.
func (o *PlanOverridesObjectChargesInner) GetMinAmountCents() int32 {
	if o == nil || IsNil(o.MinAmountCents) {
		var ret int32
		return ret
	}
	return *o.MinAmountCents
}

// GetMinAmountCentsOk returns a tuple with the MinAmountCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanOverridesObjectChargesInner) GetMinAmountCentsOk() (*int32, bool) {
	if o == nil || IsNil(o.MinAmountCents) {
		return nil, false
	}
	return o.MinAmountCents, true
}

// HasMinAmountCents returns a boolean if a field has been set.
func (o *PlanOverridesObjectChargesInner) HasMinAmountCents() bool {
	if o != nil && !IsNil(o.MinAmountCents) {
		return true
	}

	return false
}

// SetMinAmountCents gets a reference to the given int32 and assigns it to the MinAmountCents field.
func (o *PlanOverridesObjectChargesInner) SetMinAmountCents(v int32) {
	o.MinAmountCents = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *PlanOverridesObjectChargesInner) GetProperties() ChargeObjectProperties {
	if o == nil || IsNil(o.Properties) {
		var ret ChargeObjectProperties
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanOverridesObjectChargesInner) GetPropertiesOk() (*ChargeObjectProperties, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *PlanOverridesObjectChargesInner) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given ChargeObjectProperties and assigns it to the Properties field.
func (o *PlanOverridesObjectChargesInner) SetProperties(v ChargeObjectProperties) {
	o.Properties = &v
}

// GetGroupProperties returns the GroupProperties field value if set, zero value otherwise.
func (o *PlanOverridesObjectChargesInner) GetGroupProperties() []PlanCreateInputPlanChargesInnerGroupPropertiesInner {
	if o == nil || IsNil(o.GroupProperties) {
		var ret []PlanCreateInputPlanChargesInnerGroupPropertiesInner
		return ret
	}
	return o.GroupProperties
}

// GetGroupPropertiesOk returns a tuple with the GroupProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanOverridesObjectChargesInner) GetGroupPropertiesOk() ([]PlanCreateInputPlanChargesInnerGroupPropertiesInner, bool) {
	if o == nil || IsNil(o.GroupProperties) {
		return nil, false
	}
	return o.GroupProperties, true
}

// HasGroupProperties returns a boolean if a field has been set.
func (o *PlanOverridesObjectChargesInner) HasGroupProperties() bool {
	if o != nil && !IsNil(o.GroupProperties) {
		return true
	}

	return false
}

// SetGroupProperties gets a reference to the given []PlanCreateInputPlanChargesInnerGroupPropertiesInner and assigns it to the GroupProperties field.
func (o *PlanOverridesObjectChargesInner) SetGroupProperties(v []PlanCreateInputPlanChargesInnerGroupPropertiesInner) {
	o.GroupProperties = v
}

// GetTaxCodes returns the TaxCodes field value if set, zero value otherwise.
func (o *PlanOverridesObjectChargesInner) GetTaxCodes() []string {
	if o == nil || IsNil(o.TaxCodes) {
		var ret []string
		return ret
	}
	return o.TaxCodes
}

// GetTaxCodesOk returns a tuple with the TaxCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanOverridesObjectChargesInner) GetTaxCodesOk() ([]string, bool) {
	if o == nil || IsNil(o.TaxCodes) {
		return nil, false
	}
	return o.TaxCodes, true
}

// HasTaxCodes returns a boolean if a field has been set.
func (o *PlanOverridesObjectChargesInner) HasTaxCodes() bool {
	if o != nil && !IsNil(o.TaxCodes) {
		return true
	}

	return false
}

// SetTaxCodes gets a reference to the given []string and assigns it to the TaxCodes field.
func (o *PlanOverridesObjectChargesInner) SetTaxCodes(v []string) {
	o.TaxCodes = v
}

func (o PlanOverridesObjectChargesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlanOverridesObjectChargesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.BillableMetricId) {
		toSerialize["billable_metric_id"] = o.BillableMetricId
	}
	if !IsNil(o.InvoiceDisplayName) {
		toSerialize["invoice_display_name"] = o.InvoiceDisplayName
	}
	if !IsNil(o.MinAmountCents) {
		toSerialize["min_amount_cents"] = o.MinAmountCents
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.GroupProperties) {
		toSerialize["group_properties"] = o.GroupProperties
	}
	if !IsNil(o.TaxCodes) {
		toSerialize["tax_codes"] = o.TaxCodes
	}
	return toSerialize, nil
}

type NullablePlanOverridesObjectChargesInner struct {
	value *PlanOverridesObjectChargesInner
	isSet bool
}

func (v NullablePlanOverridesObjectChargesInner) Get() *PlanOverridesObjectChargesInner {
	return v.value
}

func (v *NullablePlanOverridesObjectChargesInner) Set(val *PlanOverridesObjectChargesInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanOverridesObjectChargesInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanOverridesObjectChargesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanOverridesObjectChargesInner(val *PlanOverridesObjectChargesInner) *NullablePlanOverridesObjectChargesInner {
	return &NullablePlanOverridesObjectChargesInner{value: val, isSet: true}
}

func (v NullablePlanOverridesObjectChargesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanOverridesObjectChargesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


