/*
Lago API documentation

Lago API allows your application to push customer information and metrics (events) from your application to the billing application.

API version: 0.52.0-beta
Contact: tech@getlago.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lagoapi

import (
	"encoding/json"
)

// checks if the WebhookEndpointCreateInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookEndpointCreateInput{}

// WebhookEndpointCreateInput struct for WebhookEndpointCreateInput
type WebhookEndpointCreateInput struct {
	WebhookEndpoint *WebhookEndpointCreateInputWebhookEndpoint `json:"webhook_endpoint,omitempty"`
}

// NewWebhookEndpointCreateInput instantiates a new WebhookEndpointCreateInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookEndpointCreateInput() *WebhookEndpointCreateInput {
	this := WebhookEndpointCreateInput{}
	return &this
}

// NewWebhookEndpointCreateInputWithDefaults instantiates a new WebhookEndpointCreateInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookEndpointCreateInputWithDefaults() *WebhookEndpointCreateInput {
	this := WebhookEndpointCreateInput{}
	return &this
}

// GetWebhookEndpoint returns the WebhookEndpoint field value if set, zero value otherwise.
func (o *WebhookEndpointCreateInput) GetWebhookEndpoint() WebhookEndpointCreateInputWebhookEndpoint {
	if o == nil || IsNil(o.WebhookEndpoint) {
		var ret WebhookEndpointCreateInputWebhookEndpoint
		return ret
	}
	return *o.WebhookEndpoint
}

// GetWebhookEndpointOk returns a tuple with the WebhookEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointCreateInput) GetWebhookEndpointOk() (*WebhookEndpointCreateInputWebhookEndpoint, bool) {
	if o == nil || IsNil(o.WebhookEndpoint) {
		return nil, false
	}
	return o.WebhookEndpoint, true
}

// HasWebhookEndpoint returns a boolean if a field has been set.
func (o *WebhookEndpointCreateInput) HasWebhookEndpoint() bool {
	if o != nil && !IsNil(o.WebhookEndpoint) {
		return true
	}

	return false
}

// SetWebhookEndpoint gets a reference to the given WebhookEndpointCreateInputWebhookEndpoint and assigns it to the WebhookEndpoint field.
func (o *WebhookEndpointCreateInput) SetWebhookEndpoint(v WebhookEndpointCreateInputWebhookEndpoint) {
	o.WebhookEndpoint = &v
}

func (o WebhookEndpointCreateInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookEndpointCreateInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.WebhookEndpoint) {
		toSerialize["webhook_endpoint"] = o.WebhookEndpoint
	}
	return toSerialize, nil
}

type NullableWebhookEndpointCreateInput struct {
	value *WebhookEndpointCreateInput
	isSet bool
}

func (v NullableWebhookEndpointCreateInput) Get() *WebhookEndpointCreateInput {
	return v.value
}

func (v *NullableWebhookEndpointCreateInput) Set(val *WebhookEndpointCreateInput) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookEndpointCreateInput) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookEndpointCreateInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookEndpointCreateInput(val *WebhookEndpointCreateInput) *NullableWebhookEndpointCreateInput {
	return &NullableWebhookEndpointCreateInput{value: val, isSet: true}
}

func (v NullableWebhookEndpointCreateInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookEndpointCreateInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


