/*
Lago API documentation

Lago API allows your application to push customer information and metrics (events) from your application to the billing application.

API version: 0.52.0-beta
Contact: tech@getlago.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lagoapi

import (
	"encoding/json"
	"fmt"
)

// checks if the SubscriptionsPaginated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionsPaginated{}

// SubscriptionsPaginated struct for SubscriptionsPaginated
type SubscriptionsPaginated struct {
	Subscriptions []SubscriptionObject `json:"subscriptions"`
	Meta PaginationMeta `json:"meta"`
}

type _SubscriptionsPaginated SubscriptionsPaginated

// NewSubscriptionsPaginated instantiates a new SubscriptionsPaginated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionsPaginated(subscriptions []SubscriptionObject, meta PaginationMeta) *SubscriptionsPaginated {
	this := SubscriptionsPaginated{}
	this.Subscriptions = subscriptions
	this.Meta = meta
	return &this
}

// NewSubscriptionsPaginatedWithDefaults instantiates a new SubscriptionsPaginated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionsPaginatedWithDefaults() *SubscriptionsPaginated {
	this := SubscriptionsPaginated{}
	return &this
}

// GetSubscriptions returns the Subscriptions field value
func (o *SubscriptionsPaginated) GetSubscriptions() []SubscriptionObject {
	if o == nil {
		var ret []SubscriptionObject
		return ret
	}

	return o.Subscriptions
}

// GetSubscriptionsOk returns a tuple with the Subscriptions field value
// and a boolean to check if the value has been set.
func (o *SubscriptionsPaginated) GetSubscriptionsOk() ([]SubscriptionObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subscriptions, true
}

// SetSubscriptions sets field value
func (o *SubscriptionsPaginated) SetSubscriptions(v []SubscriptionObject) {
	o.Subscriptions = v
}

// GetMeta returns the Meta field value
func (o *SubscriptionsPaginated) GetMeta() PaginationMeta {
	if o == nil {
		var ret PaginationMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *SubscriptionsPaginated) GetMetaOk() (*PaginationMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *SubscriptionsPaginated) SetMeta(v PaginationMeta) {
	o.Meta = v
}

func (o SubscriptionsPaginated) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionsPaginated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subscriptions"] = o.Subscriptions
	toSerialize["meta"] = o.Meta
	return toSerialize, nil
}

func (o *SubscriptionsPaginated) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subscriptions",
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionsPaginated := _SubscriptionsPaginated{}

	err = json.Unmarshal(bytes, &varSubscriptionsPaginated)

	if err != nil {
		return err
	}

	*o = SubscriptionsPaginated(varSubscriptionsPaginated)

	return err
}

type NullableSubscriptionsPaginated struct {
	value *SubscriptionsPaginated
	isSet bool
}

func (v NullableSubscriptionsPaginated) Get() *SubscriptionsPaginated {
	return v.value
}

func (v *NullableSubscriptionsPaginated) Set(val *SubscriptionsPaginated) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionsPaginated) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionsPaginated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionsPaginated(val *SubscriptionsPaginated) *NullableSubscriptionsPaginated {
	return &NullableSubscriptionsPaginated{value: val, isSet: true}
}

func (v NullableSubscriptionsPaginated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionsPaginated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


