/*
Lago API documentation

Lago API allows your application to push customer information and metrics (events) from your application to the billing application.

API version: 0.52.0-beta
Contact: tech@getlago.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lagoapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CouponCreateInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CouponCreateInput{}

// CouponCreateInput struct for CouponCreateInput
type CouponCreateInput struct {
	Coupon CouponCreateInputCoupon `json:"coupon"`
}

type _CouponCreateInput CouponCreateInput

// NewCouponCreateInput instantiates a new CouponCreateInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCouponCreateInput(coupon CouponCreateInputCoupon) *CouponCreateInput {
	this := CouponCreateInput{}
	this.Coupon = coupon
	return &this
}

// NewCouponCreateInputWithDefaults instantiates a new CouponCreateInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCouponCreateInputWithDefaults() *CouponCreateInput {
	this := CouponCreateInput{}
	return &this
}

// GetCoupon returns the Coupon field value
func (o *CouponCreateInput) GetCoupon() CouponCreateInputCoupon {
	if o == nil {
		var ret CouponCreateInputCoupon
		return ret
	}

	return o.Coupon
}

// GetCouponOk returns a tuple with the Coupon field value
// and a boolean to check if the value has been set.
func (o *CouponCreateInput) GetCouponOk() (*CouponCreateInputCoupon, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Coupon, true
}

// SetCoupon sets field value
func (o *CouponCreateInput) SetCoupon(v CouponCreateInputCoupon) {
	o.Coupon = v
}

func (o CouponCreateInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CouponCreateInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["coupon"] = o.Coupon
	return toSerialize, nil
}

func (o *CouponCreateInput) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"coupon",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCouponCreateInput := _CouponCreateInput{}

	err = json.Unmarshal(bytes, &varCouponCreateInput)

	if err != nil {
		return err
	}

	*o = CouponCreateInput(varCouponCreateInput)

	return err
}

type NullableCouponCreateInput struct {
	value *CouponCreateInput
	isSet bool
}

func (v NullableCouponCreateInput) Get() *CouponCreateInput {
	return v.value
}

func (v *NullableCouponCreateInput) Set(val *CouponCreateInput) {
	v.value = val
	v.isSet = true
}

func (v NullableCouponCreateInput) IsSet() bool {
	return v.isSet
}

func (v *NullableCouponCreateInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCouponCreateInput(val *CouponCreateInput) *NullableCouponCreateInput {
	return &NullableCouponCreateInput{value: val, isSet: true}
}

func (v NullableCouponCreateInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCouponCreateInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


