name: '[Ruby] CI'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'ruby/**'
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.2', '3.1', '3.0', '2.7']

    steps:
      - uses: actions/checkout@v4
        with:
          path: ./
          sparse-checkout: ruby
          sparse-checkout-cone-mode: false

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
